service:
  name: auctions-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-aws-terraform-outputs

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    DEV_AUCTIONS_TABLE_NAME: ${terraform:${self:custom.tf_workspace}:dynamodb-table-name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):NewAuctionsTableIAM}
functions:
  createAuction:
    handler: src/functions/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          cors: true

  getAuctions:
    handler: src/functions/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          cors: true

  getAuction:
    handler: src/functions/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          cors: true

  placeBid:
    handler: src/functions/placeBid.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
          cors: true

  processAuctions:
    handler: src/functions/processAuctions.handler
    events:
    #   - schedule: rate(1 minute)
      - http:
          method: PATCH
          path: /close-auction
          cors: true
custom:
  tf_workspace: s3://terraform-my-own-project/my-terraform-project