name: Terraform workspace

on:
  push:
  pull_request:
    types: [opened]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-1
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: plan
        shell: bash
        run: 
          cd infra/terraform && terraform init  && terraform plan 

      - name: deploy
        shell: bash
        run: 
          terraform apply -input=false -auto-approve       

